from . import res_partner
from . import res_bank
from . import res_partner_bank
from . import purchase_order
from . import purchase_order_line
from . import product_category
from . import product_template
from . import res_branch
from . import stock_warehouse
from . import uom_category
from . import uom_uom
from . import product_product
from . import stock_picking
from . import stock_immediate_transfer
from . import stock_backorder_confirmation
from . import res_company
from . import stock_move_line
from . import res_config_settings
from . import stock_production_lot