# Copyright 2018-2019 Ivan Yelizariev <https://it-projects.info/team/yelizariev>
# Copyright 2021 Denis Mudarisov <https://github.com/trojikman>
# License LGPL-3.0 or later (http://www.gnu.org/licenses/lgpl.html).
{
    "name": """iBOS ERP Integration""",
    "summary": """RESTful API to integrate Odoo with whatever system you need""",
    "category": "",
    "images": [],
    "version": "13.0.1.2.4",
    "application": False,
    "author": "iBOS Limited",
    "support": "apps@itpp.dev",
    "website": "",
    "license": "LGPL-3",
    "depends": ["base", "product", "stock", "purchase", "contacts", "branch", "uom"],
    "data": [
        "views/product_category.xml",
        "views/product_template.xml",
        "views/product_product.xml",
        "views/purchase_order.xml",
        #"views/purchase_order_line.xml",
        "views/res_partner.xml",
        "views/res_bank.xml",
        "views/res_partner_bank.xml",
        "views/res_branch.xml",
        "views/res_company.xml",
        "views/stock_warehouse.xml",
        "views/uom_category.xml",
        "views/uom_uom.xml",
        "views/stock_picking.xml",
        "views/stock_move.xml",
        "views/res_config_settings.xml",
        "views/stock_production_lot.xml",
    ],
    "demo": [],
    "pre_init_hook": None,
    "post_init_hook": None,
    "uninstall_hook": None,
    "auto_install": False,
    "installable": True,
}
